version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"

  service_a:
    build: ./service_a
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=localhost:9092

  service_b:
    build: ./service_b
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=localhost:9092
